version: "3.8"

services:
  fungi:
    image: fungirt/engine
    ports:
      - 8080:8080
    environment:
      APP_SECRET: sRkg7MXtfXnHzxgnffP4y0zLNgKwtcqTFzqz
      APP_KEY: RariG72w8vj0oc2cZsHpBFWgg6TtwhKzg9XG

  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
