version: "3.8"

services:
  engine:
    image: fungirt/engine
    ports:
      - 8080:8080
    environment:
      APP_SECRET: sRkg7MXtfXnHzxgnffP4y0zLNgKwtcqTFzqz
      APP_KEY: RariG72w8vj0oc2cZsHpBFWgg6TtwhKzg9XG
