version: "3.8"

services:
  fungi:
    image: fungirt/engine
    ports:
      - 8080:8080
    environment:
      WEBHOOKS_SIGNING_SECRET: G5su7d2evERPtiw27bGayzz90XBL4HD0PJr5mY
      WEBHOOKS_ENDPOINTS: http://host.docker.internal:3000/api/webhooks/fungi
      APP_SECRET: sRkg7MXtfXnHzxgnffP4y0zLNgKwtcqTFzqz
      APP_KEY: RariG72w8vj0oc2cZsHpBFWgg6TtwhKzg9XG

  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
